// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: synchronization/synchronization.proto

package synchronization

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SyncClient is the client API for Sync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncClient interface {
	SyncService(ctx context.Context, opts ...grpc.CallOption) (Sync_SyncServiceClient, error)
}

type syncClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncClient(cc grpc.ClientConnInterface) SyncClient {
	return &syncClient{cc}
}

func (c *syncClient) SyncService(ctx context.Context, opts ...grpc.CallOption) (Sync_SyncServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &Sync_ServiceDesc.Streams[0], "/synchronization.Sync/SyncService", opts...)
	if err != nil {
		return nil, err
	}
	x := &syncSyncServiceClient{stream}
	return x, nil
}

type Sync_SyncServiceClient interface {
	Send(*SyncMsg) error
	Recv() (*Alive, error)
	grpc.ClientStream
}

type syncSyncServiceClient struct {
	grpc.ClientStream
}

func (x *syncSyncServiceClient) Send(m *SyncMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *syncSyncServiceClient) Recv() (*Alive, error) {
	m := new(Alive)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SyncServer is the server API for Sync service.
// All implementations must embed UnimplementedSyncServer
// for forward compatibility
type SyncServer interface {
	SyncService(Sync_SyncServiceServer) error
	mustEmbedUnimplementedSyncServer()
}

// UnimplementedSyncServer must be embedded to have forward compatible implementations.
type UnimplementedSyncServer struct {
}

func (UnimplementedSyncServer) SyncService(Sync_SyncServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncService not implemented")
}
func (UnimplementedSyncServer) mustEmbedUnimplementedSyncServer() {}

// UnsafeSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServer will
// result in compilation errors.
type UnsafeSyncServer interface {
	mustEmbedUnimplementedSyncServer()
}

func RegisterSyncServer(s grpc.ServiceRegistrar, srv SyncServer) {
	s.RegisterService(&Sync_ServiceDesc, srv)
}

func _Sync_SyncService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServer).SyncService(&syncSyncServiceServer{stream})
}

type Sync_SyncServiceServer interface {
	Send(*Alive) error
	Recv() (*SyncMsg, error)
	grpc.ServerStream
}

type syncSyncServiceServer struct {
	grpc.ServerStream
}

func (x *syncSyncServiceServer) Send(m *Alive) error {
	return x.ServerStream.SendMsg(m)
}

func (x *syncSyncServiceServer) Recv() (*SyncMsg, error) {
	m := new(SyncMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Sync_ServiceDesc is the grpc.ServiceDesc for Sync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "synchronization.Sync",
	HandlerType: (*SyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncService",
			Handler:       _Sync_SyncService_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "synchronization/synchronization.proto",
}
